### PR TITLE
EventDataBatch BufferOverflow fix

### LINKED ISSUE #235: EventDataBatch.tryAdd throws BufferOverflowException
## Actual Behavior
1. `EventDataBatch.tryAdd` throws `java.nio.BufferOverflowException` when adding an event greater than 256KB in size.

## Expected Behavior
1. Should return `false` rather than crashing.

## Details
This is happening because the buffer allocated to encoding the message in `EventDataBatch.getSize` is limited to 256KB, which is insufficient for messages that cannot fit in the batch even by themselves.

## Versions  
- OS platform and version: N/A
- Maven package version or commit ID: 3deac08bcc9094734644fd10f0a8dd45b711b428

### PR DESCRIPTION
**Pull request by sabeegrewal**
Close #235 

When `getSize` results in a buffer overflow (i.e. when the provided `EventData` is higher than the `maxMessageSize`), we throw a `PayloadSizeExceededException`.

### CODE REVIEW

File: azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventDataBatch.java [hunk 1]
```diff
@@ -52,7 +52,13 @@ public final boolean tryAdd(final EventData eventData) {
             throw new IllegalArgumentException("eventData cannot be null");
         }
 
-        final int size = getSize(eventData, events.isEmpty());
+        final int size;
+        try {
+            size = getSize(eventData, events.isEmpty());
+        } catch (java.nio.BufferOverflowException exception) {
```
Comment (sjkwak) [inline azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventDataBatch.java]: As discussed, let's throw an exception if the size of event data exceeds max-batch size instead of returning false. Otherwise, adding an item will keep failing if the size exceeds max-batch-size. That is, if size of an input is less than max-batch-size and there is no space in the buffer, then return false. If the size of input exceeds the max-batch-size, then throw an exception so that users can fix the issue.

Comment (sabeegrewal) [reply azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventDataBatch.java]: done!
